PY_FILES = \
	./books/spiders/spider.py \
	./books/spiders/__init__.py \
	./books/settings.py \
	./books/middlewares.py \
	./books/items.py \
	./books/pipelines.py \
	./books/__init__.py

all:
	pylint $(PY_FILES)

